-- 코드를 작성해주세요
SELECT TMP.ID, 
    CASE 
        WHEN TMP.PER <= 0.25 THEN 'CRITICAL'
        WHEN TMP.PER <= 0.5 THEN 'HIGH'
        WHEN TMP.PER <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA
) AS TMP
ORDER BY ID;