-- 코드를 작성해주세요
SELECT YEAR(A.DIFFERENTIATION_DATE) AS 'YEAR', (TOP.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A JOIN
(SELECT YEAR(DIFFERENTIATION_DATE) AS 'YEAR', MAX(SIZE_OF_COLONY) AS MAX_SIZE 
 FROM ECOLI_DATA 
 GROUP BY YEAR(DIFFERENTIATION_DATE)) TOP ON YEAR(A.DIFFERENTIATION_DATE) = TOP.YEAR
 ORDER BY YEAR, YEAR_DEV